export const DEVELOPMENT_BASE_URL = 'http://localhost:8000/api/v1';
export const TOKEN_KEY = 'UNCENSORED_USER_TOKEN_KEY';
export const TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjZhMjY4ZTdlZmE0NjU3ZGIxMWQyZmYiLCJpYXQiOjE2MDA3OTI0MzB9.kVuP0oQXI_uofjenGP2cUU6rAPKDCo9lt93vuOI_3S0';